### ISSUE TITLE
Plz keep on mentaining

### ISSUE THREAD

**Issue by Dvixe** [Lavish883/LokiStream-Lite#6]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lavish883** [comment]
@Dvixe Thx for the error report form, I will use that as a template. I am maintaining the app, currently I am almost done with MAL anime integration. Let me know if you find any bugs.
