### ISSUE TITLE
Error loading page

### ISSUE THREAD

**Issue by Myst400** [Lavish883/LokiStream-Lite#8]
**Describe the bug**
Can't watch anything get "Error loading"

**To Reproduce**
Click on any anime (or even dubbed)
Click any episode
Shows error screen

**Expected behavior**
Play anime...

**Screenshots**
![Screenshot_2023-04-03-03-13-07-12_863446e6219bfd11cfa1cba33170655f](https://user-images.githubusercontent.com/93368416/229438264-9918b1bc-6881-4c2e-afff-506cffb7d8d9.jpg)

**Smartphone (please complete the following information):**
 - Device: Android
 - Version 12

**Additional context**
Did the source url break?

**Comment by Lavish883** [comment]
@Myst400 I will get working on fixing this bug please give me a few days to fix it.

**Comment by Lavish883** [comment]
@Myst400 I fixed the issue, It should work now. Thank you for reporting the issue.
