### ISSUE TITLE
The app is in a constant state of loading on the main menu where you view the anime you want to watch. Please fix, thank you.

### ISSUE THREAD

**Issue by BlackoftheDawn** [Lavish883/LokiStream-Lite#9]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lavish883** [comment]
Fixed Thank you for reporting the issue.
